---

- hosts: all # this needs to be updated if you're provisioning more than just vagrant 
  roles: 
    - role: install-generic-packages
    - role: install-node-4
      tags: 
        - node
    - role: install-memcached
    - role: install-npm-globals
    - role: install-headless-chrome
      tags: 
        - chrome
